#!/usr/bin/env bash
# displays username, user id and home directory for each line of /etc/passwd.

file_h="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$file_h"
